name: CI/CD Pipeline with vCluster

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install vCluster CLI
        uses: loft-sh/setup-loft@main
        with:
          url: ${{ secrets.LOFT_URL }}
          access-key: ${{ secrets.LOFT_ACCESS_KEY }}

      - name: Create Virtual Cluster for PR
        uses: loft-sh/create-vcluster@main
        with:
          name: pr-${{ github.event.pull_request.number }}-${{ github.sha }}-${{ github.run_id }}
          auto-cleanup: true

      - name: Deploy Application
        run: |
          kubectl apply -Rf ./k8s --context=$NAME

      - name: Wait for Deployment
        run: |
          kubectl rollout status deployment/my-app --context=$NAME

      - name: Run Tests
        run: |
          curl http://my-app.default.svc.cluster.local:30001 # Adjust as necessary based on your service configuration