name: CI/CD Pipeline with vcluster

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install vCluster CLI
        uses: loft-sh/setup-vcluster@main
      - name: Login to vCluster Platform instance
        env:
          LOFT_URL: ${{ secrets.LOFT_URL }}
          LOFT_ACCESS_KEY: ${{ secrets.LOFT_ACCESS_KEY }}
        run: vcluster login $LOFT_URL --access-key $LOFT_ACCESS_KEY
      - name: Create PR Virtual Cluster
        env:
          NAME: pr-${{ github.event.pull_request.number }}-${{ github.sha }}-${{ github.run_id }}
        run: vcluster create $NAME --project default
      
      - name: Deploy Application
        run: |
          kubectl apply -Rf ./k8s --context=$NAME

      - name: Wait for Deployment
        run: |
          kubectl rollout status deployment/my-app --context=$NAME

      - name: Run Tests
        run: |
          curl http://my-app.default.svc.cluster.local:30001 # Adjust as necessary based on your service configuration

      
      - name: Delete PR Virtual Cluster
        env:
          NAME: pr-${{ github.event.pull_request.number }}-${{ github.sha }}-${{ github.run_id }}
        run: vcluster delete $NAME --project default